// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Rare_BE.Migrations
{
    [DbContext(typeof(RareDbContext))]
    [Migration("20240914175900_subscriptionUpdate")]
    partial class subscriptionUpdate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PostTag", b =>
                {
                    b.Property<int>("PostsId")
                        .HasColumnType("integer");

                    b.Property<int>("TagsId")
                        .HasColumnType("integer");

                    b.HasKey("PostsId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("PostTag");
                });

            modelBuilder.Entity("Rare.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Label")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Label = "Drama"
                        },
                        new
                        {
                            Id = 2,
                            Label = "Arts"
                        },
                        new
                        {
                            Id = 3,
                            Label = "Technology"
                        },
                        new
                        {
                            Id = 4,
                            Label = "Astronomy"
                        },
                        new
                        {
                            Id = 5,
                            Label = "Science"
                        },
                        new
                        {
                            Id = 6,
                            Label = "Sci-Fi"
                        },
                        new
                        {
                            Id = 7,
                            Label = "Fanfic"
                        },
                        new
                        {
                            Id = 8,
                            Label = "Music"
                        },
                        new
                        {
                            Id = 9,
                            Label = "Business"
                        },
                        new
                        {
                            Id = 10,
                            Label = "Health"
                        },
                        new
                        {
                            Id = 11,
                            Label = "Travel"
                        },
                        new
                        {
                            Id = 12,
                            Label = "Politics"
                        },
                        new
                        {
                            Id = 13,
                            Label = "Sports"
                        },
                        new
                        {
                            Id = 14,
                            Label = "Culture"
                        },
                        new
                        {
                            Id = 15,
                            Label = "Food"
                        });
                });

            modelBuilder.Entity("Rare.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("PostId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("PostId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 4,
                            Content = "Sounds like a good anime",
                            CreatedOn = new DateTime(2024, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostId = 4
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 5,
                            Content = "Pitching it to Warner Brothers!",
                            CreatedOn = new DateTime(2024, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostId = 4
                        });
                });

            modelBuilder.Entity("Rare.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("integer");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("PublicationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            CategoryId = 2,
                            Content = "Mr. Bennett says that it is only if the characters are real that the novel has any chance of surviving. Otherwise, die it must. But, I ask myself, what is reality? And who are the judges of reality?",
                            ImageURL = "",
                            PublicationDate = new DateTime(2024, 8, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Mr. Bennett and Mrs. Brown"
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 3,
                            CategoryId = 10,
                            Content = "A young frog named Freddie struggles with a seemingly simple task: tying his shoes. Despite his best efforts and the helpful advice from his friends, Freddie's frustration grows as he faces a series of amusing mishaps. Ultimately, Freddie learns that perseverance and a bit of creativity can turn even the most challenging problems into opportunities for growth and friendship.",
                            ImageURL = "",
                            PublicationDate = new DateTime(2008, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Frog That Couldn't Tie His Shoes"
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 5,
                            CategoryId = 11,
                            Content = "A curious young cat named Sparky embarks on a thrilling adventure to the distant city of Timbuktu. Along the way, Sparky encounters exotic landscapes, befriends fascinating characters, and uncovers the rich cultural tapestry of the region. Through his journey, Sparky discovers that true adventure lies not just in new places, but in the friendships and experiences that shape his path.",
                            ImageURL = "",
                            PublicationDate = new DateTime(2024, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Sparky Goes to Timbuktu"
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 5,
                            CategoryId = 6,
                            Content = "Set in a post-apocalyptic world where humans have vanished, the remaining wildlife faces a mysterious crisis: birds are evolving with deformed beaks, threatening their survival. A clever raven named Rook teams up with a resourceful squirrel named Nutmeg to investigate the cause of this anomaly. As they unravel the clues, they discover that the key to restoring balance lies in a hidden human artifact, leading them on a perilous journey to save their world from impending chaos.",
                            ImageURL = "",
                            PublicationDate = new DateTime(2024, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Bird Beak Conundrum"
                        });
                });

            modelBuilder.Entity("Rare.Models.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("EndedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("FollowerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Subscriptions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 4,
                            CreatedOn = new DateTime(2024, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FollowerId = 1
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 4,
                            CreatedOn = new DateTime(2024, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FollowerId = 3
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 4,
                            CreatedOn = new DateTime(2024, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FollowerId = 5
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 2,
                            CreatedOn = new DateTime(2024, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FollowerId = 1
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 5,
                            CreatedOn = new DateTime(2024, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndedOn = new DateTime(2024, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FollowerId = 3
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 5,
                            CreatedOn = new DateTime(2024, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FollowerId = 4
                        });
                });

            modelBuilder.Entity("Rare.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Label = "America"
                        },
                        new
                        {
                            Id = 2,
                            Label = "Olympics"
                        },
                        new
                        {
                            Id = 3,
                            Label = "Election"
                        },
                        new
                        {
                            Id = 4,
                            Label = "Budget"
                        },
                        new
                        {
                            Id = 5,
                            Label = "Fusion"
                        },
                        new
                        {
                            Id = 6,
                            Label = "Moscow"
                        },
                        new
                        {
                            Id = 7,
                            Label = "Europe"
                        },
                        new
                        {
                            Id = 8,
                            Label = "Opinion"
                        },
                        new
                        {
                            Id = 9,
                            Label = "Currency"
                        },
                        new
                        {
                            Id = 10,
                            Label = "Gardening"
                        },
                        new
                        {
                            Id = 11,
                            Label = "Parenthood"
                        },
                        new
                        {
                            Id = 12,
                            Label = "DIY"
                        },
                        new
                        {
                            Id = 13,
                            Label = "Bird Beaks <>"
                        });
                });

            modelBuilder.Entity("Rare.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("Uid")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bio = "Now deceased but still at it.",
                            CreatedOn = new DateTime(2024, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "whosafraid@me.com",
                            FirstName = "Virginia",
                            ImageURL = "",
                            LastName = "Woolf"
                        },
                        new
                        {
                            Id = 2,
                            Bio = "Local weatherman turned vigilante techno DJ",
                            CreatedOn = new DateTime(2019, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "alexjones@gmail.com",
                            FirstName = "Alex",
                            ImageURL = "",
                            LastName = "Jones"
                        },
                        new
                        {
                            Id = 3,
                            Bio = "Shoulda bought Apple",
                            CreatedOn = new DateTime(1998, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "funkyfrog@yahoo.com",
                            FirstName = "Taylor",
                            ImageURL = "",
                            LastName = "Harrison"
                        },
                        new
                        {
                            Id = 4,
                            Bio = "I'm watching anime",
                            CreatedOn = new DateTime(2023, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "lastnamejoseph@aol.com",
                            FirstName = "Odie",
                            ImageURL = "",
                            LastName = "Dicaprio"
                        },
                        new
                        {
                            Id = 5,
                            Bio = "Born in 1955, Quincy Quayle grew up in the city of New Mammoth, Montana. He is predeceased by carnival employees Jack and Barbara. No relation.",
                            CreatedOn = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "notdan@notdan.com",
                            FirstName = "Quincy",
                            ImageURL = "",
                            LastName = "Quayle"
                        });
                });

            modelBuilder.Entity("PostTag", b =>
                {
                    b.HasOne("Rare.Models.Post", null)
                        .WithMany()
                        .HasForeignKey("PostsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rare.Models.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Rare.Models.Comment", b =>
                {
                    b.HasOne("Rare.Models.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rare.Models.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("Rare.Models.Post", b =>
                {
                    b.HasOne("Rare.Models.User", "Author")
                        .WithMany("Posts")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rare.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Rare.Models.Subscription", b =>
                {
                    b.HasOne("Rare.Models.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("Rare.Models.Post", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("Rare.Models.User", b =>
                {
                    b.Navigation("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
